### ISSUE TITLE
Grafana 4 collection selection is not working

### ISSUE THREAD

**Issue by nokernel** [dalmatinerdb/dalmatinerdb-datasource#19]
The plugin seems to have some issue on grafana 4.

In the UI when adding a metric, in the FROM textbox 'select collection', you are unable to select a collection.

It is able to find the available collections, but you can't select any of them. The textbox just revert to 'select collection' when you select one or type it's name in.

Running dalmatiner-fe version : dev-fcb043a, Wed Apr 5 07:34:34 2017 +0200

Grafana version : 4.1.1-1484211277

**Comment by Licenser** [comment]
Hi! Yes this plugin is build for Grafana 3. The whole javascript shebang is not my strong side but I'd be happy to accept pull requests for updates to Grafana 4.

**Comment by nokernel** [comment]
I am in the same position :). It's ok I am not in a hurry.

From what I can see this plugin is using the "demo" json plugin from grafana?

**Comment by DvdGiessen** [comment]
I just came across this bug as well, and the fix actually turned out to be quite trivial. The root cause is the updated lodash library version in Grafana 4, in which a function alias used in the plugin no longer exists. Changing to the non-aliased function name resolves the issue and the plugin works fine in Grafana 4.

Opened pull #20 for the fix.

**Comment by Licenser** [comment]
Thanks @DvdGiessen :D

**Comment by nokernel** [comment]
Oh nice :+1: Obviously I was going nowhere when trying to find the issue in the plugin. Thanks @DvdGiessen
